### ISSUE TITLE
NoneType' object is not subscriptable on StashInterface Initialization

### ISSUE THREAD

**Issue by merqwury** [stg-annon/stashapp-tools#2]
I've been trying to use stashapp-tools after a while (which used to work perfectly), however, I'm getting the following error when trying to initialize the StashInterface class:

e Could not connect to Stash at http://<URL>:<PORT>/graphql e 'NoneType' object is not subscriptable

When trying to access GraphQL directly from http://<URL>:<PORT>/playground that works perfectly fine.

Any ideas what might have changed? Thanks

**Comment by merqwury** [comment]
Actually looks like the problem is in stashapi - classes.py 

`		if response.status_code == 200:
			result_data = defaultify(result.get("data"))
			return result_data['data']`
			
I'm on 0.2.9

**Comment by merqwury** [comment]
Installing directly from git seems to resolve this issue as I've noticed there have been changes made recently to solve this problem.

pip install git+https://github.com/stg-annon/stashapp-tools.git

Can we please update pip to pick up a new version?

Thanks

**Comment by stg-annon** [comment]
pip has been updated to `0.2.10` which should address this feel free to reopen if you're still having issues
