### ISSUE TITLE
adding performers to scenes

### ISSUE THREAD

**Issue by SaracenRhue** [stg-annon/stashapp-tools#4]
How can I add performers to scenes? I've tried to update the scene like this:
```
stash.update_scene({'id': 1, 'performers': [{ 'id': 10 }, { 'id': 220 }]})
```
But I get a unknown filed error

**Comment by stg-annon** [comment]
@SaracenRhue you would want to pass a [**SceneUpdateInput**](https://github.com/stashapp/stash/blob/develop/graphql/schema/types/scene.graphql#L115-L147) object which would look like the following in your case

```python

stash.update_scene({
  'id': 1,
  'performer_ids': [10,220]
})

```

**Comment by SaracenRhue** [comment]
Thanks for the quick reply
