### ISSUE TITLE
[Bug] find_image(id) always return None

### ISSUE THREAD

**Issue by HijackHornet** [stg-annon/stashapp-tools#5]
No matter the id of provided, find_image will return None even though the id exists
Tried 
find_image('1234') > None
find_image(1234) > GRAPHQL_ERROR: must not be null ['findImage', 'file', 'mod_time']

**Comment by stg-annon** [comment]
@HijackHornet I've tested https://github.com/stg-annon/stashapi/tree/7291dbf239c25520856dda114badb221df843c89 locally which seems to resolve the problem, can you test for your use case?

**Comment by stg-annon** [comment]
should be resolved with latest release, please reopen if you continue to have issues

**Comment by HijackHornet** [comment]
Yes thanks
